<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE map [
<!ELEMENT map (tile+)>
<!ATTLIST map rows CDATA #REQUIRED colls CDATA #REQUIRED held_x CDATA #REQUIRED held_y CDATA #REQUIRED held_dir CDATA #REQUIRED max_inv CDATA #REQUIRED>
<!ELEMENT tile EMPTY>
<!ATTLIST tile x CDATA #REQUIRED y CDATA #REQUIRED value CDATA #REQUIRED>
]>
<map rows="10" colls="14" held_x="0" held_y="4" held_dir="2" max_inv="10">
<tile x="0" y="0" value="1"></tile>
<tile x="0" y="1" value="0"></tile>
<tile x="0" y="2" value="0"></tile>
<tile x="0" y="3" value="0"></tile>
<tile x="0" y="4" value="2"></tile>
<tile x="0" y="5" value="2"></tile>
<tile x="0" y="6" value="2"></tile>
<tile x="0" y="7" value="0"></tile>
<tile x="0" y="8" value="0"></tile>
<tile x="0" y="9" value="0"></tile>
<tile x="0" y="10" value="0"></tile>
<tile x="0" y="11" value="2"></tile>
<tile x="0" y="12" value="0"></tile>
<tile x="0" y="13" value="0"></tile>
<tile x="1" y="0" value="0"></tile>
<tile x="1" y="1" value="0"></tile>
<tile x="1" y="2" value="0"></tile>
<tile x="1" y="3" value="2"></tile>
<tile x="1" y="4" value="2"></tile>
<tile x="1" y="5" value="0"></tile>
<tile x="1" y="6" value="0"></tile>
<tile x="1" y="7" value="0"></tile>
<tile x="1" y="8" value="0"></tile>
<tile x="1" y="9" value="2"></tile>
<tile x="1" y="10" value="1"></tile>
<tile x="1" y="11" value="0"></tile>
<tile x="1" y="12" value="0"></tile>
<tile x="1" y="13" value="0"></tile>
<tile x="2" y="0" value="0"></tile>
<tile x="2" y="1" value="1"></tile>
<tile x="2" y="2" value="0"></tile>
<tile x="2" y="3" value="0"></tile>
<tile x="2" y="4" value="2"></tile>
<tile x="2" y="5" value="0"></tile>
<tile x="2" y="6" value="0"></tile>
<tile x="2" y="7" value="1"></tile>
<tile x="2" y="8" value="0"></tile>
<tile x="2" y="9" value="0"></tile>
<tile x="2" y="10" value="0"></tile>
<tile x="2" y="11" value="0"></tile>
<tile x="2" y="12" value="2"></tile>
<tile x="2" y="13" value="0"></tile>
<tile x="3" y="0" value="0"></tile>
<tile x="3" y="1" value="0"></tile>
<tile x="3" y="2" value="1"></tile>
<tile x="3" y="3" value="0"></tile>
<tile x="3" y="4" value="2"></tile>
<tile x="3" y="5" value="0"></tile>
<tile x="3" y="6" value="0"></tile>
<tile x="3" y="7" value="0"></tile>
<tile x="3" y="8" value="0"></tile>
<tile x="3" y="9" value="0"></tile>
<tile x="3" y="10" value="0"></tile>
<tile x="3" y="11" value="0"></tile>
<tile x="3" y="12" value="1"></tile>
<tile x="3" y="13" value="0"></tile>
<tile x="4" y="0" value="0"></tile>
<tile x="4" y="1" value="0"></tile>
<tile x="4" y="2" value="0"></tile>
<tile x="4" y="3" value="0"></tile>
<tile x="4" y="4" value="0"></tile>
<tile x="4" y="5" value="1"></tile>
<tile x="4" y="6" value="0"></tile>
<tile x="4" y="7" value="2"></tile>
<tile x="4" y="8" value="2"></tile>
<tile x="4" y="9" value="0"></tile>
<tile x="4" y="10" value="0"></tile>
<tile x="4" y="11" value="2"></tile>
<tile x="4" y="12" value="0"></tile>
<tile x="4" y="13" value="0"></tile>
<tile x="5" y="0" value="0"></tile>
<tile x="5" y="1" value="0"></tile>
<tile x="5" y="2" value="0"></tile>
<tile x="5" y="3" value="2"></tile>
<tile x="5" y="4" value="0"></tile>
<tile x="5" y="5" value="0"></tile>
<tile x="5" y="6" value="0"></tile>
<tile x="5" y="7" value="1"></tile>
<tile x="5" y="8" value="0"></tile>
<tile x="5" y="9" value="0"></tile>
<tile x="5" y="10" value="0"></tile>
<tile x="5" y="11" value="2"></tile>
<tile x="5" y="12" value="2"></tile>
<tile x="5" y="13" value="0"></tile>
<tile x="6" y="0" value="1"></tile>
<tile x="6" y="1" value="0"></tile>
<tile x="6" y="2" value="1"></tile>
<tile x="6" y="3" value="0"></tile>
<tile x="6" y="4" value="0"></tile>
<tile x="6" y="5" value="0"></tile>
<tile x="6" y="6" value="0"></tile>
<tile x="6" y="7" value="0"></tile>
<tile x="6" y="8" value="0"></tile>
<tile x="6" y="9" value="0"></tile>
<tile x="6" y="10" value="2"></tile>
<tile x="6" y="11" value="2"></tile>
<tile x="6" y="12" value="0"></tile>
<tile x="6" y="13" value="0"></tile>
<tile x="7" y="0" value="2"></tile>
<tile x="7" y="1" value="0"></tile>
<tile x="7" y="2" value="0"></tile>
<tile x="7" y="3" value="0"></tile>
<tile x="7" y="4" value="0"></tile>
<tile x="7" y="5" value="0"></tile>
<tile x="7" y="6" value="0"></tile>
<tile x="7" y="7" value="0"></tile>
<tile x="7" y="8" value="0"></tile>
<tile x="7" y="9" value="0"></tile>
<tile x="7" y="10" value="0"></tile>
<tile x="7" y="11" value="0"></tile>
<tile x="7" y="12" value="0"></tile>
<tile x="7" y="13" value="0"></tile>
<tile x="8" y="0" value="0"></tile>
<tile x="8" y="1" value="1"></tile>
<tile x="8" y="2" value="0"></tile>
<tile x="8" y="3" value="0"></tile>
<tile x="8" y="4" value="1"></tile>
<tile x="8" y="5" value="0"></tile>
<tile x="8" y="6" value="0"></tile>
<tile x="8" y="7" value="1"></tile>
<tile x="8" y="8" value="0"></tile>
<tile x="8" y="9" value="1"></tile>
<tile x="8" y="10" value="0"></tile>
<tile x="8" y="11" value="0"></tile>
<tile x="8" y="12" value="0"></tile>
<tile x="8" y="13" value="1"></tile>
<tile x="9" y="0" value="0"></tile>
<tile x="9" y="1" value="0"></tile>
<tile x="9" y="2" value="2"></tile>
<tile x="9" y="3" value="0"></tile>
<tile x="9" y="4" value="0"></tile>
<tile x="9" y="5" value="0"></tile>
<tile x="9" y="6" value="0"></tile>
<tile x="9" y="7" value="0"></tile>
<tile x="9" y="8" value="0"></tile>
<tile x="9" y="9" value="0"></tile>
<tile x="9" y="10" value="0"></tile>
<tile x="9" y="11" value="0"></tile>
<tile x="9" y="12" value="0"></tile>
<tile x="9" y="13" value="0"></tile>
</map>
